Overlap
jlmelville/rnndescent pull request #5
Opened 2021-07-21 12:19 UTC by vspinu

POC. Needs tests.

2021-07-21 15:13 UTC, jlmelville reviewed
Thank you @vspinu, this is very thorough. As an explanation, the version of the Hamming distance that currently exists is designed to replicate the results from [Annoy](https://github.com/spotify/annoy), but the [pynndescent definition](https://github.com/lmcinnes/pynndescent/blob/d0ed50bd3e78316d41f53025d5cb5dcfbb17d835/pynndescent/distances.py#L170-L176) is similar to your version.

A few things:

1. The `pynndescent` version of `hamming` seems to normalize the results by the length of the input vectors. This doesn't seem to be in the official definition of the Hamming distance though (and also adds a division). I don't see a compelling reason to add the normalization, do you agree?
1. Should this version become the implementation for `"hamming"`? Maybe the binary-only version can be renamed to `"bhamming"`.
1. What kind of data is this intended for? Integers? Do you have any sample data with expected input and output for testing?
1. Do you want to add yourself as a contributor in the `Authors@R` section of the `DESCRIPTION`?

2021-07-22 09:58 UTC, vspinu commented
> This doesn't seem to be in the official definition of the Hamming distance though (and also adds a division). I don't see a compelling reason to add the normalization, do you agree?

Yes. I agree. Normalization is super easy outside of the routine and I would rather have it as part of more generic #3 weighting feature.

> Should this version become the implementation for "hamming"? Maybe the binary-only version can be renamed to "bhamming".

Yes, that would make more sense to me. The package is still on CRAN and I guess not widely used as yet, so breaking should be fine. 

>What kind of data is this intended for? Integers? 

Yes. I didn't want to add a separate entry point for integers but I think it should be done to avoid the implicit Rcpp conversion. 

> Do you have any sample data with expected input and output for testing?

No, but I will create once we agree on the final.

> Do you want to add yourself as a contributor in the Authors@R section of the DESCRIPTION?

Thanks, but I think this small change is not worthy of authorship.

2021-07-22 13:34 UTC, vspinu commented
I have renamed `orverlap`->`hamming` and `hamming`->`bhamming` and added tests.

2021-07-22 15:13 UTC, jlmelville requested changes
This looks good in terms of implementation.

Can we change the tests to not use a loop? Particularly in test code, I prefer copy-and-paste as it makes it much easier to identify which tests failed. In the specific case of `test_descent_hamming.R`, I'd be happy to see that split into two files (i.e. create a `test_descent_bhamming.R` file).

2021-07-23 10:58 UTC, vspinu commented
Because of the different context you will get an output like 

```
✖ |   8 1     | NN descent bhamming
───────────────────────────────────────────────────────────────────────────────────────────
Failure (test_descent_hamming.R:42:3): (code run outside of `test_that()`)
sum(bitdata) not equal to 791.
1/1 mismatches
[1] 790 - 791 == -1

```
Looks as clear as it can be to me.

For the loops in the other places I can add `label` argument to the expect_equal so the output will look like 

```
Failure (test_brute_force.R:76:3): (code run outside of `test_that()`)
hamming: not equal to `bit6q_hdsum`.
1/1 mismatches
[1] 1275 - 1986 == -711
```

Not a big deal anyhow, whatever you choose. Just want to double check.

2021-07-23 14:19 UTC, jlmelville commented
My experience with tests in loops is that when something goes wrong with one of the loop items, you end up having to manually unroll the loop to separate the passing and failing items. So I now prefer to not have a loop at all.

2021-07-23 14:29 UTC, vspinu commented
Ok. I have unrolled all the loops.

2021-07-24 16:29 UTC, jlmelville requested changes
Based on the discussion in #6, I think changes to the roxygen docs should be done as part of a separate PR. Can you go back to having the documentation inline rather than using `@inheritParams`? Sorry to be a pain.

2021-09-18 18:59 UTC, jlmelville commented
@vspinu I have integrated the changes from this PR manually. I have also added you as a contributor in the `DESCRIPTION`. Thanks for the PR, sorry it took so long to get this merged.

2021-09-18 18:59 UTC, closed without merging

2021-09-20 14:26 UTC, vspinu commented
@jlmelville Sorry for not coming back on this one. Vacation came in and after I couldn't find time to revisit it. 

Unfortunately we also moved away from the nearest neighbor in our project and I might not have enough drive to pursue other improvements that we have discussed here and there. I will let you know if I do :)